config/routes.rb
Rails.application.routes.draw do
  root to: "snippets#index"

  resources :snippets, path: "/", param: :sid, constraints: { sid: /[a-zA-Z0-9\-]{32,36}/ }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snippet.rb
# frozen_string_literal: true

class Snippet < ApplicationRecord
  PERMITTED_PARAMS = %i[content].freeze

  def sid
    id&.delete("-")
  end

  def to_param
    sid
  end

  def to_key
    [sid]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  prepend_view_path Rails.root.join("frontend")
end

app/controllers/snippets_controller.rb
# frozen_string_literal: true

class SnippetsController < ApplicationController
  before_action :fetch_snippet, only: %i[show edit update destroy]

  def index
    @snippets = Snippet.all
  end

  def show; end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.save
      render :edit
    else
      render :new
    end
  end

  def edit; end

  def update
    @snippet.assign_attributes(snippet_params)
    @snippet.save
    render :edit
  end

  def destroy
    @snippet.destroy
    redirect_to snippets_path, status: 302
  end

  private

  def fetch_snippet
    @snippet ||= Snippet.find(params[:sid])
  end

  def snippet_params
    params.require(:snippet).permit(Snippet::PERMITTED_PARAMS)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snip</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag "application" %>
    <%= stylesheet_pack_tag "client-bundle" %>
  </head>

  <body>
    <div cclass="container">
      <%= yield %>
    </div>
    <%= react_component("SnippetApp", props: {}, prerender: true) %>
    <%= javascript_pack_tag "client-bundle" %>
    <%#= javascript_pack_tag "application" %>
  </body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet, url: url do |f| %>
  <% if @snippet.errors.any? %>
    <div>
      <ul>
        <% @snippets.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_area :content, required: true, autofocus: true %>
  <% if @snippet.new_record? %>
    <%= f.submit "Create Snippet" %>
    <%= link_to "Cancel", snippets_path %>
  <% else %>
    <%= f.submit "Update Snippet" %>
    <%= link_to "Cancel", snippet_path(@snippet) %>
  <% end %>
<% end %>

app/views/snippets/_header.html.erb
<%= link_to "Snippets", snippets_path %>
<%= link_to "Edit", edit_snippet_path(@snippet) %>
<%#= link_to "Delete", snippet_path(@snippet), method: :delete, data: { confirm: "Delete?" } %>

app/views/snippets/edit.html.erb
Edit Snippet
<%= render "snippets/form", url: snippet_path(@snippet) %>

app/views/snippets/index.html.erb
<%= link_to "New Snippet", new_snippet_path %>
<ul>
  <% @snippets.each do |snippet| %>
    <li>
      <%= link_to snippet_path(snippet) do %>
        <%= snippet.sid %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/snippets/new.html.erb
New Snippet
<%= render "snippets/form", url: snippets_path(@snippet) %>

app/views/snippets/show.html.erb
<%= render "header" %>
<pre>
  <%= @snippet.content %>
</pre>